branch-defaults:
  default:
    environment: nodeapp-dev
    group_suffix: null
  master:
    environment: nodeapp-dev
global:
  application_name: nodeapp
  branch: null
  default_ec2_keyname: null
  default_platform: Docker running on 64bit Amazon Linux 2
  default_region: us-west-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  repository: null
  sc: null
  workspace_type: Application
